build:
  packages:
    - build-essential
    - libjpeg-dev
    - zlib1g-dev
    - libfreetype6-dev
    - python3-dev
startCommand: "pip install --upgrade pip setuptools wheel && streamlit run app.py"
